[tool.black]
line-length = 100
target-version = ["py311"]
include = "\\.py$"

[tool.ruff]
line-length = 100
target-version = "py311"
select = ["E", "F", "I", "UP", "B"]
ignore = ["E501"]
exclude = [
  ".venv",
  "agentik-b2b-app/agentik-frontend",
  "frontend",
]
