name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  backend:
    name: Backend - Build Sanity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Import check
        run: python - << 'PY'
import importlib
import sys
for m in [
    'app.main', 'app.auth', 'app.database', 'app.redis_client',
    'app.models', 'app.services.supplier_discovery'
]:
    try:
        importlib.import_module(m)
        print('OK', m)
    except Exception as e:
        print('FAIL', m, e)
        sys.exit(1)
PY

  frontend:
    name: Frontend - Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Enable corepack
        run: corepack enable
      - name: Install deps
        working-directory: frontend
        run: pnpm install --frozen-lockfile
      - name: Build
        working-directory: frontend
        env:
          VITE_API_URL: http://localhost:8000
          VITE_SUPABASE_URL: https://example.supabase.co
          VITE_SUPABASE_ANON_KEY: dummy
        run: pnpm build --skip-types || npm run build

