name: Build and Push Docker Images

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*.*.*'
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_BACKEND: ${{ secrets.DOCKERHUB_USERNAME }}/agentik-backend
  IMAGE_FRONTEND: ${{ secrets.DOCKERHUB_USERNAME }}/agentik-frontend
  IMAGE_AGENTS: ${{ secrets.DOCKERHUB_USERNAME }}/agentik-agents

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Compute tags
        id: meta
        run: |
          SHA=${GITHUB_SHA::7}
          echo "sha=$SHA" >> $GITHUB_OUTPUT
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
          else
            TAG=latest
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build & push backend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_BACKEND }}:${{ steps.meta.outputs.tag }}
            ${{ env.IMAGE_BACKEND }}:${{ steps.meta.outputs.sha }}

      - name: Build & push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_FRONTEND }}:${{ steps.meta.outputs.tag }}
            ${{ env.IMAGE_FRONTEND }}:${{ steps.meta.outputs.sha }}

      - name: Build & push agents
        uses: docker/build-push-action@v6
        with:
          context: ./agent_orchestrator
          file: ./agent_orchestrator/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_AGENTS }}:${{ steps.meta.outputs.tag }}
            ${{ env.IMAGE_AGENTS }}:${{ steps.meta.outputs.sha }}

